# fly.toml app configuration file generated for follow-bot-job on 2023-06-03T19:03:31+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "follow-bot-job"
primary_region = "yyz"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = ["app"]